### ISSUE TITLE
Crashing/Dropping players while connecting

### ISSUE THREAD

**Issue by vavavr00m** [stevenwdv/rs-biter-home-finder#1]
Per the Factorio support team:

The mod rs-biter-home-finder is filling the global script table with too much data,
And the saving is failing to allocate enough memory

If you remove the mod, the game should perform better

RAM Usage before and after removal:

![image](https://user-images.githubusercontent.com/4675132/222435499-37ff3b8a-46e1-44ba-8d68-580aea5f27be.png)

![image](https://user-images.githubusercontent.com/4675132/222435549-bfe04c3e-3f5c-4efe-b26f-cb284fa5b3f1.png)

**Comment by stevenwdv** [comment]
Wait 25GB?! That's not good 😅 Sorry for that.
What I do is keep track of the spawner of each biter in `unit_spawners`, so that also biters in a group that split off can be linked to their spawner. When the biter dies, it should then remove the entry. It seems that that doesn't happen in your case, I guess? I don't know how that is possible. The event I listen for is [`on_entity_died`](https://lua-api.factorio.com/latest/events.html#on_entity_died).

**Comment by stevenwdv** [comment]
Is there anything weird happening with biters in your world that could cause this?

**Comment by vavavr00m** [comment]
I'm not really sure. I can email you the stuff that was sent to Factorio's support team if you would like to take a look at it. Please  do let me know your email address (there's stuff that I couldn't post here.)

**Comment by stevenwdv** [comment]
I think the issue is that biters can despawn, but then `on_entity_died` seems to not fire, meaning they are not removed from the list. I asked on the forum if there is a way to still keep track of these entities being removed from the world.

**Comment by vavavr00m** [comment]
If it helps, sometimes admins wipe off the biters for various reasons. Here are some of the options:

1. Console command: [Kill all biters on enemy force](https://wiki.factorio.com/Console#Kill_all_biters_on_the_%22enemy%22_force)

![image](https://user-images.githubusercontent.com/4675132/223140053-b1a44eb6-296b-4e73-9d98-04c9da55c8b2.png)

3. Console command: [Kill all nearby enemies](https://wiki.factorio.com/Console#Kill_all_nearby_enemies)

![image](https://user-images.githubusercontent.com/4675132/223140252-2ecae99a-fb14-40de-8625-a40c661931a9.png)

5. 'Reset to default biters' button in Enemy Race Manager* (issue [here](https://github.com/heyqule/enemy_race_manager/issues/34), however, save file no longer has rs biter home finder installed)
6. 'Nuke all enemy units around you in 32 tile radius. This is to kill over level units caused by a map processing bug' button in Enemy Race Manager*
7. 'Clean idle biter' button in Enemy Race Manager*

![image](https://user-images.githubusercontent.com/4675132/223139006-ef7cd56f-463e-4e6d-94d0-d5a53c0594d0.png)

**Comment by stevenwdv** [comment]
With both of these commands, `on_entity_destroyed` does fire, if registered. But I'm not sure how to check for despawning entities. Haven't seen it fire without these commands though.

**Comment by stevenwdv** [comment]
Btw, did you use these commands / mods in the affected world?

I can't get biters to despawn and don't know how often they do this, so maybe that is not the issue.
EDIT: I think I may have gotten it to work. Any any case, `on_entity_destroyed` does fire here, so I'll switch to that and remove non-existing biters from the list in existing worlds.

**Comment by vavavr00m** [comment]
All were used at some point.

**Comment by stevenwdv** [comment]
Thanks for the info! Do you still have the version of the world with the problem? If so, could you test this version and report how many units it says it removed from the list?
[rs-biter-home-finder_1.1.1.zip](https://github.com/stevenwdv/rs-biter-home-finder/files/10899616/rs-biter-home-finder_1.1.1.zip) (place in `%appdata%\Factorio\mods`)

**Comment by vavavr00m** [comment]
Tested in single player, the game froze before I could even do/type anything but was able to see an automatic message from Enemy Race Manager:

![image](https://user-images.githubusercontent.com/4675132/223164949-49db3a04-0fff-4e36-b363-48f992335f66.png)

Here's the save file:

Link: https://mega.nz/file/3VdUiYhR
Decryption: xwZTc5x1MPbiKq93k96uVCefzqLqlrKyduJuY-brGpM

**Comment by stevenwdv** [comment]
Ok, thanks for trying! I tried loading it but I don't have a beast of a PC so I didn't even get past the loading screen. Anyway, maybe the 1.1.1 version that I published works better because it applied the correction immediately. Otherwise removing (and re-adding, if you like) the mod should work, as you already knew.

On a different note, I just thought that I don't know if `on_entity_destroyed` fires for enemies entities if that mod is then removed, so maybe I should always check for killed entities after a mod change, instead of just when updating to the new version.

**Comment by stevenwdv** [comment]
Done. Hopefully everything works correctly now.

**Comment by vavavr00m** [comment]
It seems this [issue](https://mods.factorio.com/mod/rs-biter-home-finder/discussion/640657b27fad5d8aaba8db01) is related to this new version. Thanks for trying to fix, will check after the linked issue has also been fixed.

**Comment by stevenwdv** [comment]
Oops, fixed now! Haven't extensively tested the mod myself. Apparently `on_entity_destroyed` is fired for registrations by other mods as well.

**Comment by vavavr00m** [comment]
Cool, thanks! Will report if there are any issues.
